### ISSUE TITLE
Principal=>subordinate coordination for logrotation (grafana-agent causing a lot of unreleased files and huge syslog)

### ISSUE THREAD

**Issue by taurus-forever** [canonical/grafana-agent-operator#153]
### Bug Description

Hi,

Please check the complete issue description in PostgreSQL repo: 
https://github.com/canonical/postgresql-operator/issues/524

TL;DR: PostgreSQL charm rotates logs but doesn't send any signals to subordinated grafana-agent causing a lot of unreleased files and huge syslog => downtime.

It is a cross-team ticket to build a solution here. 

### To Reproduce

See steps to reproduce in https://github.com/canonical/postgresql-operator/issues/524

### Environment

See Versions in https://github.com/canonical/postgresql-operator/issues/524

### Relevant log output

```shell
No relevant logs output.
```

### Additional context

Proposals:
* (preferred) subordinated charm(s) should bring/install logrotate config, so principal charm will execute all of them.
* principal charm should (somehow) detects subordinates and inform them (somehow) using signal (SIGHUP?)
Better ideas are welcome!

**Comment by taurus-forever** [comment]
@simskij do you have good ideas how to proceed here?
DB charm should somehow aware about COS promtail to SIGHUP it properly.

**Comment by lucabello** [comment]
@taurus-forever Do you think this would be solved by not getting all the files from `/var/log/**` and instead only get a few?

**Comment by taurus-forever** [comment]
@lucabello AFAIK, no. The grafana-agent charm / promtail binary ([did](https://github.com/canonical/postgresql-k8s-operator/pull/486)?) read some log files from disk (to send them to Loki). PostgreSQL charm rotates logs, but didn't send any lignals to COS to close the current description and reopen the file (as the old one moved to archive folder).

IMHO, we have two options:
 * send all logs through pebble and never read logs on disk. AFAIK it is a current COS plan. Pros: VM has no Pebble. Journald has performance issues, etc.
 * team principal/PostgreSQL charm to send signals on logrorate to subordinated/grafa-agent.
 * ...
Better ideas are welcome!

**Comment by sed-i** [comment]
- Grafana folks [recommend](https://grafana.com/docs/loki/latest/send-data/promtail/logrotation/) using the "rename and create" rotation strategy over "copy and truncate". Do you know what rotation strategy is set up for postgresql? Is that configurable on your side?
- Are you saying that slurping the archive `patroni/patroni.log.*`  is incorrect, and we should only be reading the one file `patroni/patroni.log`? That could be related to the glob `"/var/log/**/*log"` we have in place. But I'm surprised that filenames such as `patroni.log.6545` or `patroni.log.10080` would match the glob. I confirmed that python's glob meets my expectation (`[print(p.name) for p in Path(".").glob("**/*log")]`) but not sure how it's impl'd in gagent.

I'd appreciate your input on the above @taurus-forever.

**Comment by dragomirp** [comment]
> * Grafana folks [recommend](https://grafana.com/docs/loki/latest/send-data/promtail/logrotation/) using the "rename and create" rotation strategy over "copy and truncate". Do you know what rotation strategy is set up for postgresql? Is that configurable on your side?

Patroni should be using an extended version of Python's [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler). Python's docs indicate “rename and create”. We can only configure size and amount of files to keep.

Postgresql is configured to keep a week's worth of per minute logs that are truncated each minute. This is behaviour configured by us, but it is spec behaviour so discussions would be necessary to change it.

Both Patroni and Postgresql try to keep about a week's worth of per minute logs, so that should be about 10k files for each.

> * Are you saying that slurping the archive `patroni/patroni.log.*`  is incorrect, and we should only be reading the one file `patroni/patroni.log`? That could be related to the glob `"/var/log/**/*log"` we have in place. But I'm surprised that filenames such as `patroni.log.6545` or `patroni.log.10080` would match the glob. I confirmed that python's glob meets my expectation (`[print(p.name) for p in Path(".").glob("**/*log")]`) but not sure how it's impl'd in gagent.

I don't know how the agent detects log changes, but for Patroni only the last few logs should be relevant, the deeper backlog was likely already synced and shouldn't be changing. For Postgresql things are trickier, since the files are the same (`postgresql-%w_%H%M.log`) but will be overwritten when the same time comes.

**Comment by Vultaire** [comment]
I'm hoping this is still on peoples' radar - this interaction between postgresql and grafana-agent is creating truly excessive logging in some environments.  I'm seeing roughly 8 gigs of log lines a day just related to events related to the patroni log files.  This is quickly filling the disk of the hosts in one of the clouds I am working on.  (10,080 log lines * roughly 300 characters per line * 2,800 times a day (twice a minute) = 8,467,200,000 bytes as a rough estimate)

**Comment by Vultaire** [comment]
Adding additional context, per discussion with the obs team: here is the related job in /etc/grafana-agent.yaml:

```
    - job_name: charmed-postgresql-common-var-log-patroni
      pipeline_stages:
      - drop:
          expression: .*file is a directory.*
      relabel_configs:
      - replacement: /patroni
        source_labels:
        - __path__
        target_label: path
      static_configs:
      - labels:
          __path__: /snap/grafana-agent/51/shared-logs/patroni/**
          job: charmed-postgresql-common-var-log-patroni
          juju_application: postgresql
          juju_charm: grafana-agent
          juju_model: landscape-dev
          juju_model_uuid: 31a78a72-cb68-4796-84ff-29a4b0f5321f
          juju_unit: postgresql/1
          snap_name: charmed-postgresql
        targets:
        - localhost
```
