### ISSUE TITLE
Loki Alerts are fired for each principal application instead only once

### ISSUE THREAD

**Issue by cbartz** [canonical/grafana-agent-operator#159]
### Bug Description

We have following alert rule: https://github.com/canonical/github-runner-operator/blob/b70a5353deb280738339f5878e8fa57c45c3cc78/src/loki_alert_rules/failure.rules#L4-L11 to detect runner crashes for a particular self-hosted runner deployment.

This gets topology labels injected by the grafana agent

```
kubectl exec -ti loki-0 -c loki --   cat /loki/rules/fake/prod-github-runner_4572b1cc_grafana-agent_alert.rules
...
- name: foo_bar_5572b1cc_grafana-agent_foo-bar_5572b1cc_edge_github-runner-failure_alerts_alerts
  rules:
  - alert: Crashed runner
    annotations:
      summary: A runner in unit {{ $labels.juju_unit }} crashed.
    expr: (sum_over_time({filename="/var/log/github-runner-metrics.log", juju_application="grafana-agent",
      juju_charm="grafana-agent", juju_model="foo-bar", juju_model_uuid="4572b1cc-0a39-40b7-818d-c68ed553f11a"}
      | json event="event",crashed_runners="crashed_runners" | event="reconciliation"
      | unwrap crashed_runners[1h]) > 0)
    for: 0s
    labels:
      juju_application: edge
      juju_charm: github-runner
      juju_model: foo-bar
      juju_model_uuid: 5572b1cc-0a39-40b7-818d-c68ed553f11a
      severity: high
```

The Grafana agent is integrated with 3 main applications. Once an alert is triggered, it is duplicated to all 3 main applications (although it only applies to one). The alerts all contain `juju_application=principal-charm` instead of `juju_application=grafana-agent` (as it is displayed in grafana and loki).

It appears that the principal application name is used for the `juju_application` label in the fired alert instead of the subordinate one, which would lead to deduplication because the same alert is fired.

### To Reproduce

Create a simple alert rule for a charm. Deploy the charm three times, and integrate it with the grafana agent, which in turn should be integrated with loki, and loki with the alertmanager. Note that the alert is triggered for each main application, not just once for the grafana agent.

### Environment

juju 3.1.8 , grafana-agent rev 164

### Relevant log output

```shell
not applicable
```

**Comment by sed-i** [comment]
Multiple principles is not yet supported this way.
See #11.

**Comment by sed-i** [comment]
Btw, does each principal come with their own rules? If not, then relating gagent to just one of the principals would be enough to get the node-exporter stuff.

**Comment by cbartz** [comment]
> Multiple principles is not yet supported this way. See #11.
> 
> Juju supports deploying multiple principals to the same machine (--to), but if we relate them to the same subordinate, or even if we deploy the same subordinate under two different names, the snap would overwrite/uninstall each other, as well as the grafana agent config file.
> 

@sed-i 

I think we are misunderstanding, the principal are all on different machines. 
Each principal is a deployment of the same charm. Please see https://pastebin.canonical.com/p/NnYwT4ybv5/ for the actual deployment. You see three github-runner charm deployments on different machines integrated with a grafana agent. 

> Btw, does each principal come with their own rules? If not, then relating gagent to just one of the principals would be enough to get the node-exporter stuff.

Yes, they have the same rules.  But they all have to be integrated with grafana-agent. E.g. we have three charm deployments A,B,C, and they are all integrated with grafana-agent X. If we would only integrate A with grafana-agent X, then the logs and metrics for B and C would be missing.

**Comment by lucabello** [comment]
Could you give us a screenshot of Alertmanager showing the alerts firing with the labels expanded, and a screenshot of Prometheus showing the results of querying that metric name?

**Comment by cbartz** [comment]
Hi @lucabello , sure here are the screenshots.

First three screenshots show the alert notifications in mattermost channel:

![Screenshot from 2024-09-09 09-54-57](https://github.com/user-attachments/assets/4335b950-7465-48da-b0d2-5908b1aaf2da)
![Screenshot from 2024-09-09 09-55-17](https://github.com/user-attachments/assets/3fbd00e4-0512-4fe3-8ef0-3fe1e77af740)
![Screenshot from 2024-09-09 09-55-23](https://github.com/user-attachments/assets/95c06c40-6b66-40d8-acac-fd039a7774f4)

You see that the alert is reported for the `large, noble-large and xlarge` applications. The reason is that these integrations are all integrated with the same grafana agent. 

The log (which comes from Loki) is only issued once by the same grafana-agent, and the log contains the grafana-agent as `juju_application`.
![Screenshot from 2024-09-09 10-00-00](https://github.com/user-attachments/assets/e9c5a17a-8471-4782-8e1e-4e9d66d6e14a)

So there is a drift between the value of `juju_application` in the fired alerts and the value of `juju_application` in the logs, causing the duplication of the fired alert. If the fired alert would also contain the grafana-agent as `juju_application`, it would not be duplicated.

**Comment by MichaelThamm** [comment]
I tried to reproduce this with no success. Here is my environment (see references section as well):

![Image](https://github.com/user-attachments/assets/3fb3d7c0-0595-4817-8fad-48c0394a688a)

![Image](https://github.com/user-attachments/assets/ad9af035-d17f-4a48-9914-76ca722cd441)

As you can see, each principal is in its own machine and only the units which match the alert rule are shown in Alertmanager excluding `gagent/14` (a freshly deployed instance of gagent), since it did not have any error logs.

If we compare this environment with the one in the [OP pastebin](https://pastebin.canonical.com/p/NnYwT4ybv5/), then we can say that:
- `zoo` -> `large`, i.e. the principal charm
- `gagent` -> `grafana-agent-without-dashboard`, i.e. the subordinate charm

This works for me for a Loki alert rule query like in the OP environment, I suspect this is an error in the way the OP query is written which collapses the unit information.

## Environment reproducer

In k8s model (`microk8s:cos`):
`curl -L https://raw.githubusercontent.com/canonical/cos-lite-bundle/main/overlays/offers-overlay.yaml -O && juju deploy cos-lite --trust --channel latest/edge --overlay ./offers-overlay.yaml && rm offers-overlay.yaml`

In LXD model (`gagent-bundle.yaml`):
```yaml
default-base: ubuntu@22.04/stable
saas:
  loki-logging:
    url: microk8s:admin/cos.loki-logging
applications:
  gagent:
    charm: grafana-agent
  zoo:
    charm: zookeeper
    channel: 3/stable
    revision: 149
    num_units: 2
relations:
- - zoo:cos-agent
  - gagent:cos-agent
- - gagent:logging-consumer
  - loki-logging:logging
```
Deploy with:
`juju deploy ./gagent-bundle.yaml --trust`

Then open Grafana UI to check the query for the `high_error_rate` alert rule. I then had to generate some errors for some (not all) units.

## References
- [LXD juju status](https://pastebin.canonical.com/p/8Sm4F55q6x/)
- [microk8s juju status](https://pastebin.canonical.com/p/TVVYQX92dN/)

**Comment by MichaelThamm** [comment]
> [!TIP]
> I suspect this is an error in the way the query is written, which collapses the unit information. This is likely not a bug so I will close the issue and feel free to re-open if needed @cbartz.

To investigate that loki alert rules are being forwarded to loki via grafana-agent and alerted on a per-unit basis, I created a dummy loki alert rule in the github-runner charm:

```
groups:
  - name: github-runner-dummy
    rules:
      - alert: Dummy rule
        expr: |
          count_over_time({filename="/var/log/dummy-metrics.log"} | json event="event" | event="dummy_event" [1h]) > 0
        labels:
            severity: high
            type: runner-capacity
        for: 0s
```

which I trigger for only the `ghr/1` unit by executing `jssh ghr/1 bash` and writing logs to `/var/log/dummy-metrics.log`:

`echo "{\"event\": \"dummy_event\", \"duration\": $((RANDOM % 300 + 1)), \"timestamp\": \"$(date +'%Y-%m-%dT%H:%M:%S%z')\"}" | sudo tee -a /var/log/dummy-metrics.log > /dev/null`

Which immediately triggers the alert rule in the Grafana UI

![Image](https://github.com/user-attachments/assets/0829d6c0-d00b-4ef7-96ab-ea0d149652ad)

And in Alertmanager, the alert's labels include `gagent/1` which is subordinate to `ghr/1`; the unit that triggered the alert.

![Image](https://github.com/user-attachments/assets/0e73d828-b59d-4aa3-8d81-aa49524e27f6)

## References

```
Model  Controller  Cloud/Region         Version  SLA          Timestamp
cp     lxd         localhost/localhost  3.6.3    unsupported  08:57:59-04:00

SAAS                             Status  Store       URL
loki-logging                     active  microk8s-1  admin/cos.loki-logging
prom                             active  microk8s-1  admin/cos.prometheus
prometheus-receive-remote-write  active  microk8s-1  admin/cos.prometheus-receive-remote-write

App     Version  Status   Scale  Charm          Channel        Rev  Exposed  Message
gagent           active       2  grafana-agent  latest/stable  456  no       grafana-dashboards-provider: off, tracing: off
ghr              blocked      2  github-runner                   9  no       Invalid Github config, Missing path configuration

Unit         Workload  Agent  Machine  Public address  Ports  Message
ghr/1*       blocked   idle   3        10.50.128.3            Invalid Github config, Missing path configuration
  gagent/1*  active    idle            10.50.128.3            grafana-dashboards-provider: off, tracing: off
ghr/2        blocked   idle   4        10.50.128.168          Invalid Github config, Missing path configuration
  gagent/2   active    idle            10.50.128.168          tracing: off, grafana-dashboards-provider: off

Machine  State    Address        Inst id        Base          AZ  Message
3        started  10.50.128.3    juju-df439b-3  ubuntu@22.04      Running
4        started  10.50.128.168  juju-df439b-4  ubuntu@22.04      Running

Integration provider                                  Requirer                  Interface                Type         Message
gagent:peers                                          gagent:peers              grafana_agent_replica    peer         
ghr:cos-agent                                         gagent:cos-agent          cos_agent                subordinate  
loki-logging:logging                                  gagent:logging-consumer   loki_push_api            regular      
```

**Comment by MichaelThamm** [comment]
@cbartz I included an annotation in the dummy alert rule of:

```yaml
        annotations:
            summary: A runner in unit {{ $labels.juju_unit }} crashed.
```

which references `{{ $labels.juju_unit }}` and I get this result in alertmanager:

![Image](https://github.com/user-attachments/assets/8f99e967-4d7f-4c82-81e8-b4d464e4ef17)

This shows that we still only get the alert in Alertmanager for the unit (principal) which is triggering the alert and not each principal. Instead of seeing the charm's name in the value for `{{ $labels.juju_unit }}` we instead get the grafana-agent app name which is not ideal, but can still be correlated to its principal charm.

## References

With a LXD bundle:
```yaml
default-base: ubuntu@22.04/stable
saas:
  loki-logging:
    url: microk8s-1:admin/cos.loki-logging
applications:
  gagent:
    charm: grafana-agent
    channel: latest/stable
    revision: 456
    trust: true
  ghr:
    charm: local:github-runner-0
    num_units: 2
    to:
    - "0"
    - "1"
    constraints: arch=amd64
    storage:
      runner: rootfs,1,1024M
    trust: true
machines:
  "0":
    constraints: arch=amd64
  "1":
    constraints: arch=amd64
relations:
- - ghr:cos-agent
  - gagent:cos-agent
- - gagent:logging-consumer
  - loki-logging:logging
```
