### ISSUE TITLE
Username, password from grafana-cloud-integrator not being rendered in the grafana-agent config

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-operator#203]
Username, password from grafana-cloud-integrator not being rendered in the grafana-agent config.

https://github.com/canonical/grafana-agent-operator/blob/4d94da5a68e14ba08cec9cd01d3de6b9c8e7f711/src/grafana_agent.py#L659-L664

## Reproduce
Deploy the following bundle and inspect the rendered `/etc/grafana-agent.yaml`.
The relation data is in place, but the creds aren't written to the yaml file.

```yaml
default-base: ubuntu@22.04/stable
applications:
  ga:
    charm: grafana-agent
    channel: latest/edge
    revision: 299
  gci:
    charm: grafana-cloud-integrator
    channel: latest/edge
    revision: 21
    num_units: 1
    to:
    - "0"
    options:
      loki-url: http://exmaple.com
      password: passwd
      username: admin
    constraints: arch=amd64
  ubu:
    charm: ubuntu
    channel: latest/stable
    revision: 25
    num_units: 3
    to:
    - "4"
    - "5"
    - "6"
    constraints: arch=amd64
    storage:
      block: loop,100M
      files: rootfs,100M
machines:
  "0":
    constraints: arch=amd64
  "4":
    constraints: arch=amd64
  "5":
    constraints: arch=amd64
  "6":
    constraints: arch=amd64
relations:
- - ubu:juju-info
  - ga:juju-info
- - ga:grafana-cloud-config
  - gci:grafana-cloud-config
```

Potentially related to https://github.com/canonical/grafana-cloud-integrator/issues/18.
