### ISSUE TITLE
bug: high_error_rate.rule incorrectly references "varlog"

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/grafana-agent-operator#276]
### Bug Description

The [loki alert high_error_rate.rule](https://github.com/canonical/grafana-agent-operator/blob/f7d2107980a58ab7cfc57618f923f791f9e0a849/src/loki_alert_rules/high_error_rate.rule#L2) incorrectly references the job name in the expression.

Incorrect:
`expr: count_over_time({job="varlogs"} |= "error" [1h]) > 120`
Corrected:
`expr: count_over_time({job="varlog"} |= "error" [1h]) > 120`

This leads to false confidence because the alert rule will never fire, rendering it useless and harmful.

### To Reproduce

In k8s model (`microk8s:cos`):
`curl -L https://raw.githubusercontent.com/canonical/cos-lite-bundle/main/overlays/offers-overlay.yaml -O && juju deploy cos-lite --trust --channel latest/edge --overlay ./offers-overlay.yaml && rm offers-overlay.yaml`

In LXD model (`gagent-bundle.yaml`):
```yaml
default-base: ubuntu@22.04/stable
saas:
  loki-logging:
    url: microk8s:admin/cos.loki-logging
applications:
  gagent:
    charm: grafana-agent
  zoo:
    charm: zookeeper
    channel: 3/stable
    revision: 149
    num_units: 1
relations:
- - zoo:cos-agent
  - gagent:cos-agent
- - gagent:logging-consumer
  - loki-logging:logging
```
Deploy with:
`juju deploy ./gagent-bundle.yaml --trust`

Then open Grafana UI to check the query for the high_error_rate alert rule:

![Image](https://github.com/user-attachments/assets/b0dd8389-413d-4937-8317-f312c2c1fb07)

Switch the query to `job="varlog"`:

![Image](https://github.com/user-attachments/assets/2afcac46-4de1-4c92-9e06-e3519a19d61b)

### Environment

See above

### Relevant log output

```shell
see above
```
