### ISSUE TITLE
Investigate if we need a "high rate of error logs" alert

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-operator#296]
### Enhancement Proposal

When we split the k8s and vm charms to separate repos, we mistakenly left one alert in the k8s charm without bringing it to the vm charm:

```yaml
alert: HostHighLogErrorRate
expr: count_over_time({job="varlog"} |= "error" [1h]) > 100
for: 0m
labels:
  severity: warning
annotations:
  summary: High error rate in logs (instance {{ $labels.instance }})
  description: "High error rate in logs\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

The alert rule [was removed](https://github.com/canonical/grafana-agent-k8s-operator/pull/375) from the k8s charm and [wasn't added](https://github.com/canonical/grafana-agent-operator/pull/272) to this vm charm.

The idea of "high rate of error logs" seems important, but "`100`" is an arbitrary threshold.

Changing this alert to account a "moving window context", e.g. rate([5m]) > 10*rate([5m] offset 5m) is slightly better, but the factor, e.g. 10, is still arbitrary and does not robustly address legitimate spikes.
