### ISSUE TITLE
Duplicated jobs for logs when using `log_slots`

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/grafana-agent-operator#56]
### Bug Description

When I am trying to use the `log_slots` for a snap that provides two slots, for example,

```yaml
# in snapcraft.yaml
...
slots:
  ovn-logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/log/ovn
  ovs-logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/log/openvswitch 
...
```

and in the charm, I used the slots:

```python
# in ./src/charm.py
self._grafana_agent = COSAgentProvider(
    ...
    log_slots=["openstack-hypervisor:ovn-logs", "openstack-hypervisor:ovs-logs"],
    ...
)
```

The `logs` section of `/etc/grafana-agent.yaml` contains duplicated jobs:

```yaml
logs:
    ...
    - job_name: openstack-hypervisor
      pipeline_stages:
      - drop:
          expression: .*file is a directory.*
      relabel_configs:
      - replacement: /openvswitch
        source_labels:
        - __path__
        target_label: path
      static_configs:
      - labels:
          __path__: /snap/grafana-agent/13/shared-logs/openvswitch/**
          job: openstack-hypervisor
          juju_model: controller
          juju_model_uuid: d451ba9f-c875-4845-8564-adc06a1880a7
        targets:
        - localhost
    - job_name: openstack-hypervisor
      pipeline_stages:
      - drop:
          expression: .*file is a directory.*
      relabel_configs:
      - replacement: /openvswitch
        source_labels:
        - __path__
        target_label: path
      static_configs:
      - labels:
          __path__: /snap/grafana-agent/13/shared-logs/openvswitch/**
          job: openstack-hypervisor
          juju_model: controller
          juju_model_uuid: d451ba9f-c875-4845-8564-adc06a1880a7
        targets:
        - localhost
 ```

### To Reproduce

See bug description

### Environment

N/A

### Relevant log output

```shell
N/A
```
